### PR TITLE
build: give HuaweiCloud repo workflow write permissions

### LINKED ISSUE #66: Publish Snapshot Build workflow is not working
# Feature Request

An error is thrown. e.g.:
https://github.com/eclipse-edc/Technology-HuaweiCloud/actions/runs/10937470211

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_Are there any requirements?_

## Solution Proposal

_If possible, provide a (brief!) solution proposal._

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

give HuaweiCloud repo workflow write permissions

## Why it does that

it needs those

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes https://github.com/eclipse-edc/Technology-HuaweiCloud/issues/66

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Comment by netomi** [comment]
actually the OP of https://github.com/eclipse-edc/Technology-HuaweiCloud/pull/68 is correct. You have to grant the called workflow the required permissions.

Your organization grants by default read only permissions to all workflows and I would strongly advise to keep it that way. It usually much less work to add the required permissions on a workflow basis instead of just granting write by default and then fix them all together at a later time when we are asking all our project to use read by default as this is the best practice.

As you already use read by now, it does not really make sense to go back to write.

**Comment by ndr-brt** [comment]
> actually the OP of [eclipse-edc/Technology-HuaweiCloud#68](https://github.com/eclipse-edc/Technology-HuaweiCloud/pull/68) is correct. You have to grant the called workflow the required permissions.
> 
> Your organization grants by default read only permissions to all workflows and I would strongly advise to keep it that way. It usually much less work to add the required permissions on a workflow basis instead of just granting write by default and then fix them all together at a later time when we are asking all our project to use read by default as this is the best practice.
> 
> As you already use read by now, it does not really make sense to go back to write.

all the other repos have "write", if that's not a best practice we should change them back to "read", and have to update all of the specific workflow, right?

**Comment by netomi** [comment]
yes indeed, in the long term we would like that all projects / repositories use read by default, however I understand that there is effort involved, so we also work on tools to help you doing that. Having said that, whenever there is a chance to already use read, do it as it will save you work in the long run imho.

**Comment by ndr-brt** [comment]
Got it, thanks for your explaination  
in any case that write permission was not really needed :sweat_smile: .

**Pull request closed without merging**
