### PR TITLE
feat: create compatibility tests repository

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

create compatibility tests repository

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Comment by wolf4ood** [comment]
Hi @netomi 

what's still missing for this PR?

Thanks :)

**Review by mbarbero — DISMISSED** [review]

**Comment by netomi** [comment]
usually we let a project lead approve requests for new repos.

**Comment by mbarbero** [comment]
@wolf4ood, are you sure you need the `default_workflow_permissions` set to `write`?

**Comment by wolf4ood** [comment]
@mbarbero 

i copied and paste from the other ones, but i think in this case it's not really necessary i can remove that

**Review by netomi — APPROVED** [review]

**Comment by wolf4ood** [comment]
@mspiekermann  

can you check this? :)

**Review by mspiekermann — APPROVED** [review]

**Pull request merged**
